# -*- coding: utf-8 -*-
#
# This file is part of Flask-Notifications
# Copyright (C) 2013, 2014, 2015 CERN.
#
# Flask-Notifications is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

sudo: false

language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install --upgrade pip
  - pip install coveralls pep257
  - pip install pytest pytest-pep8 pytest-cov pytest-cache
  - pip install -e .[docs]

services:
  - redis

script:
  - pep257 flask_notifications
  - "sphinx-build -qnNW docs docs/_build/html"
  - python -m smtpd -n -c "DebuggingServer" "0.0.0.0:25" &
  - python setup.py test

after_success:
  - coveralls

notifications:
  email: false
