# -*- coding: utf-8 -*-
#
# This file is part of Flask-Notifications
# Copyright (C) 2015 CERN.
#
# Flask-Notifications is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

web:
  build: .
  command: python examples/simple/app.py
  ports:
   - "8080:8080"
  volumes:
   - .:/code
  links:
   - worker
   - redis
   - smtp
  environment: 
   - REDIS_URL=redis://redis:6379/0
   - SMTP_SERVER=smtp

worker:
  build: .
  command: celery worker -A celery_worker.celery --workdir=examples/simple/ -P gevent --loglevel=debug
  links:
   - redis
   - smtp
  environment: 
   - REDIS_URL=redis://redis:6379/0
   - SMTP_SERVER=smtp

redis:
  image: redis

smtp:
  image: jlynn/python-smtp
